services:
  nextcloud:
    image: nextcloud
    labels:
      # Habilitar Traefik para este servicio llamado "nextcloud"
      - traefik.enable=true
      # Definir el puerto dentro del servicio de Docker a utilizar
      - traefik.http.services.nextcloud.loadbalancer.server.port=80
      # Hacer que Traefik utilice este dominio en HTTP (en Traefik se ha definido el entrypo>
      - traefik.http.routers.nextcloud-http.entrypoints=http
      - traefik.http.routers.nextcloud-http.rule=Host(`nextcloud2.rgmf.es`)
      # Usar la red públic "traefik-public" (declarada debajo)
      - traefik.docker.network=traefik-public
      # Hacer que Traefik use este dominio in HTTPS
      - traefik.http.routers.nextcloud-https.entrypoints=https
      - traefik.http.routers.nextcloud-https.rule=Host(`nextcloud2.rgmf.es`)
      - traefik.http.routers.nextcloud-https.tls=true
      # Usar el resolver crado en Traefik llamado "le" (Let's Encrypt)
      - traefik.http.routers.nextcloud-https.tls.certresolver=le
      # Middleware "https-redirect" para redirigir tráfico HTTP a HTTPS
      - traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.nextcloud-https-redirect.redirectscheme.permanent=true
      # Middleware para redirigir HTTP (router "app-http" creado arriba) a HTTPS (recién cre>
      - traefik.http.routers.nextcloud-http.middlewares=nextcloud-https-redirect

    networks:
      - traefik-public
      - nextcloud-network
    volumes:
      - ./nextcloud_data:/var/www/html
    env_file:
      - .env
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=nextcloud_db
    depends_on:
      - nextcloud_db

  nextcloud_db:
    image: mysql
    container_name: nextcloud_db
    networks:
      - nextcloud-network
    volumes:
      - ./nextcloud_db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}

volumes:
  nextcloud_data:
  nextcloud_db_data:

networks:
  traefik-public:
    external: true
  nextcloud-network:
    driver: bridge
